service: serverless-playlister
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: eu-west-2
  timeout: 600

plugins:
  - serverless-python-requirements

functions:
  bbc-to-youtube-playlister:
    handler: handler.run
    events:
      - httpApi:
          path: /
          method: post
  rateHandler:
    handler: handler.run
    events:
      - schedule: cron(15 3 ? * MON *)      # every Monday at 03:15 AM
